#!/usr/bin/env python3
# Build the public Wiki from the small JSON catalogs.
# Projects sit above categories so every project can grow its own Wiki structure.
# Nada Vfx currently has Effects, Modifiers and Vanilla Set.

from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / "wiki"
DATA = WIKI / "data"

effects = json.loads((DATA / "effects.json").read_text(encoding="utf-8"))
modifiers = json.loads((DATA / "modifiers.json").read_text(encoding="utf-8"))
projects = json.loads((DATA / "projects.json").read_text(encoding="utf-8"))

GOOGLE_FONTS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link href="https://fonts.googleapis.com/css2?'
    'family=Pixelify+Sans:wght@400;500;600&family=Inter:wght@400;500;600;700&display=swap" '
    'rel="stylesheet">'
)

GENERATED_NOTE = (
    "<!-- Generated by tools/build_wiki.py. "
    "Edit wiki/data or the generator instead of hand-editing this page. -->"
)


def esc(value: object) -> str:
    return html.escape(str(value))


def source_text(effect: dict) -> str:
    source = effect["source"]
    if source.get("prefab"):
        path = f' / {source["path"]}' if source.get("path") else ""
        return f'{source["prefab"]}{path}'
    if source.get("material"):
        return f'Material: {source["material"]}'
    return "TBD"


def root_prefix(depth: int) -> str:
    return "../" * (depth + 1)


def module_tabs(depth: int) -> str:
    root = root_prefix(depth)
    wiki_href = "index.html" if depth == 0 else "../index.html"
    return (
        '<nav class="module-tabs" aria-label="Modules">'
        f'<a class="module-tab workbench" href="{root}index.html">naomi\'s workbench</a>'
        f'<a class="module-tab wiki active" href="{wiki_href}" aria-current="page">wiki</a>'
        f'<a class="module-tab channels" href="{root}channels.html">channels</a>'
        '</nav>'
    )


def module_header(title: str, description: str, icon: str, depth: int, update_key: str = "") -> str:
    root = root_prefix(depth)
    update_attr = f' data-update-key="{esc(update_key)}"' if update_key else ""
    return f'''
<header class="module-header">
  <div class="module-title-row"{update_attr}>
    <img class="module-icon" src="{root}assets/ui/{icon}" alt="" aria-hidden="true">
    <h1 class="module-title" data-new-badge-target>{esc(title)}</h1>
  </div>
  <p class="module-description">{esc(description)}</p>
</header>
'''


def site_footer(*, valheim: bool = False) -> str:
    parts = [
        '<footer class="site-footer" aria-label="Copyright and attribution">',
        '<p>© 2026 Naomi Nada · original content unless otherwise noted.</p>'
    ]
    if valheim:
        parts.append(
            '<p>Valheim © Iron Gate AB. Nada VFX is an independent project and is not affiliated with Iron Gate.</p>'
        )
    parts.append('</footer>')
    return ''.join(parts)


def shell(title: str, body_classes: str, depth: int = 0) -> str:
    root = root_prefix(depth)
    wiki_css = "assets/wiki.css" if depth == 0 else "../assets/wiki.css"
    return (
        '<!doctype html>\n'
        f'{GENERATED_NOTE}\n'
        '<html lang="en"><head>'
        '<meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f'{GOOGLE_FONTS}'
        f'<link rel="stylesheet" href="{root}assets/site-shell.css">'
        f'<link rel="stylesheet" href="{wiki_css}">'
        f'<link rel="icon" href="{root}assets/favicon.png" type="image/png">'
        f'<script defer src="{root}assets/site-state.js"></script>'
        f'<script defer src="{root}assets/site.js"></script>'
        f'<title>{esc(title)}</title>'
        f'</head><body class="wiki-page {body_classes}"><main class="page">'
        f'{module_tabs(depth)}'
    )


def write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def project_selector() -> str:
    parts = [
        '<section class="wiki-project-select" aria-label="Select a Wiki project">',
        '<div class="wiki-project-select-control">',
        '<select class="wiki-project-select-menu" data-project-nav aria-label="Select a project">',
        '<option value="" selected disabled>[Select a Project]</option>'
    ]

    for status in ("active", "archived"):
        label = status.title()
        parts.append(f'<optgroup label="{label}">')
        for project in projects:
            if project["status"] != status:
                continue
            parts.append(
                f'<option value="{esc(project["id"])}.html">{esc(project["name"])}</option>'
            )
        parts.append('</optgroup>')

    parts.extend(['</select>', '</div>', '</section>'])
    return "".join(parts)


def project_wiki_body(project: dict) -> str:
    if project["id"] != "nada-vfx":
        return '<div class="project-empty">No public Wiki entries here yet.</div>'

    available = sum(1 for effect in effects if effect["availability"] == "Available")
    upcoming = sum(1 for effect in effects if effect["availability"] == "Upcoming")
    return f'''
<div class="wiki-track">
  <a class="wiki-track-row effects" href="effects/index.html">
    <img class="wiki-track-icon" src="../assets/ui/effects.svg" alt="" aria-hidden="true">
    <span class="wiki-track-name">effects</span>
    <span class="wiki-track-summary">Standalone effects and Orbitals.</span>
    <span class="wiki-track-count">{len(effects)} entries · {available} available · {upcoming} upcoming</span>
  </a>
  <a class="wiki-track-row modifiers" href="modifiers/index.html">
    <img class="wiki-track-icon" src="../assets/ui/modifiers.svg" alt="" aria-hidden="true">
    <span class="wiki-track-name">modifiers</span>
    <span class="wiki-track-summary">Controls used across the effect library.</span>
    <span class="wiki-track-count">{len(modifiers)} entries</span>
  </a>
  <a class="wiki-track-row vanilla" href="vanilla-set.html">
    <img class="wiki-track-icon" src="../assets/ui/vanilla.svg" alt="" aria-hidden="true">
    <span class="wiki-track-name">vanilla set</span>
    <span class="wiki-track-summary">The original Valheim sources Nada Vfx rebuilds at runtime.</span>
    <span class="wiki-track-count">{len(effects)} source entries</span>
  </a>
</div>
'''


# ---- Wiki project selector -------------------------------------------------
page = shell("wiki — naomi's workbench", "wiki-home-page")
page += module_header("wiki", "Project references.", "wiki.svg", 0)
page += project_selector()
page += site_footer() + '</main></body></html>'
write(WIKI / "index.html", page)


# ---- Project Wiki landings -------------------------------------------------
for project in projects:
    page = shell(f'{project["name"]} — wiki', "wiki-project-page", 0)
    page += f'<div class="breadcrumb"><a href="index.html">wiki</a> / {esc(project["name"])}</div>'
    page += module_header(project["name"], project["description"], project["icon"], 0)
    page += project_wiki_body(project)
    page += site_footer(valheim=project["id"] == "nada-vfx") + '</main></body></html>'
    write(WIKI / f'{project["id"]}.html', page)


# ---- Effects ---------------------------------------------------------------
page = shell("effects — Nada Vfx wiki", "effects-page", 1)
page += '<div class="breadcrumb"><a href="../index.html">wiki</a> / <a href="../nada-vfx.html">Nada Vfx</a> / effects</div>'
page += module_header("effects", "Visual effects currently available or planned for Nada Vfx.", "effects.svg", 1)

for category in ("Standalone", "Orbital"):
    page += f'<h2 class="section-title" id="{category.lower()}">{category} effects</h2><div class="section-rule"></div><div class="grid">'
    for effect in effects:
        if effect["category"] != category:
            continue
        modifier_count = len(effect["modifiers"]) if effect["modifiers"] else "—"
        page += f'''
<a class="card" data-update-key="effect:{esc(effect['id'])}" href="{esc(effect['id'])}.html">
  <div class="card-body">
    <div class="card-top">
      <h3>{esc(effect['name'])}</h3>
      <span class="tag {effect['availability'].lower()}">{esc(effect['availability'])}</span>
    </div>
    <p>{esc(effect['description'])}</p>
    <div class="card-meta"><span>{modifier_count} modifiers</span><span>{esc(effect['category'])}</span></div>
    <div class="card-source"><div class="label">Vanilla source</div><div class="value">{esc(source_text(effect))}</div></div>
  </div>
</a>
'''
    page += '</div>'
page += site_footer(valheim=True) + '</main></body></html>'
write(WIKI / "effects" / "index.html", page)

for effect in effects:
    source = effect["source"]
    page = shell(f'{effect["name"]} — Nada Vfx wiki', "effects-page", 1)
    page += f'<div class="breadcrumb"><a href="../index.html">wiki</a> / <a href="../nada-vfx.html">Nada Vfx</a> / <a href="index.html">effects</a> / {esc(effect["name"])}</div>'
    page += module_header(effect["name"], effect["description"], "effects.svg", 1, update_key=f"effect:{effect['id']}")
    page += f'''
<div class="detail-hero">
  <div class="preview">Preview clip coming</div>
  <aside class="facts">
    <div class="fact"><div class="label">Status</div><div class="value"><span class="tag {effect['availability'].lower()}">{esc(effect['availability'])}</span></div></div>
    <div class="fact"><div class="label">Type</div><div class="value">{esc(effect['category'])}</div></div>
    <div class="fact"><div class="label">Vanilla source</div><div class="value">{esc(source_text(effect))}</div>{f'<div class="source-note">{esc(source["note"])}</div>' if source.get("note") else ''}</div>
  </aside>
</div>
<h2 class="section-title">Modifiers</h2><div class="section-rule"></div><div class="chips">
'''
    if effect["modifiers"]:
        page += "".join(f'<span class="chip">{esc(name)}</span>' for name in effect["modifiers"])
    else:
        page += '<span class="chip">To be defined</span>'
    page += '</div>' + site_footer(valheim=True) + '</main></body></html>'
    write(WIKI / "effects" / f'{effect["id"]}.html', page)


# ---- Vanilla Set -----------------------------------------------------------
page = shell("vanilla set — Nada Vfx wiki", "vanilla-set-page", 0)
page += '<div class="breadcrumb"><a href="index.html">wiki</a> / <a href="nada-vfx.html">Nada Vfx</a> / vanilla set</div>'
page += module_header("vanilla set", "The vanilla Valheim sources Nada Vfx rebuilds at runtime.", "vanilla.svg", 0)
page += '<p class="vanilla-note">Each source entry shows the original in-game source Nada Vfx works from. Original Valheim visual assets are by Iron Gate unless otherwise noted.</p><div class="list">'
for effect in effects:
    page += f'''
<a class="list-row" data-update-key="effect:{esc(effect['id'])}" href="effects/{esc(effect['id'])}.html">
  <div><div class="list-name">{esc(effect['name'])}</div><div class="muted">{esc(effect['category'])}</div></div>
  <div><span class="tag {effect['availability'].lower()}">{esc(effect['availability'])}</span></div>
  <div><div class="label">Vanilla source</div><div class="list-source">{esc(source_text(effect))}</div></div>
</a>
'''
page += '</div>' + site_footer(valheim=True) + '</main></body></html>'
write(WIKI / "vanilla-set.html", page)


# ---- Modifiers -------------------------------------------------------------
page = shell("modifiers — Nada Vfx wiki", "modifiers-page", 1)
page += '<div class="breadcrumb"><a href="../index.html">wiki</a> / <a href="../nada-vfx.html">Nada Vfx</a> / modifiers</div>'
page += module_header("modifiers", "Controls used to shape, move, recolor, and animate Nada Vfx effects.", "modifiers.svg", 1)
page += '<div class="grid">'
for modifier in modifiers:
    applies_to = sum(1 for effect in effects if modifier["name"] in effect["modifiers"])
    page += f'''
<a class="card" data-update-key="modifier:{esc(modifier['id'])}" href="{esc(modifier['id'])}.html">
  <div class="card-body">
    <h3>{esc(modifier['name'])}</h3>
    <p>{esc(modifier['description'])}</p>
    <div class="card-meta"><span>{applies_to} effects</span></div>
  </div>
</a>
'''
page += '</div>' + site_footer(valheim=True) + '</main></body></html>'
write(WIKI / "modifiers" / "index.html", page)

for modifier in modifiers:
    applies_to = [effect for effect in effects if modifier["name"] in effect["modifiers"]]
    page = shell(f'{modifier["name"]} — Nada Vfx wiki', "modifiers-page", 1)
    page += f'<div class="breadcrumb"><a href="../index.html">wiki</a> / <a href="../nada-vfx.html">Nada Vfx</a> / <a href="index.html">modifiers</a> / {esc(modifier["name"])}</div>'
    page += module_header(modifier["name"], modifier["description"], "modifiers.svg", 1, update_key=f"modifier:{modifier['id']}")
    page += f'''
<div class="detail-hero">
  <div class="preview">Modifier clip coming</div>
  <aside class="facts">
    <div class="fact"><div class="label">Used by</div><div class="value">{len(applies_to)} current effects</div></div>
    <div class="fact"><div class="label">Type</div><div class="value">Shared modifier</div></div>
  </aside>
</div>
<h2 class="section-title">Used by</h2><div class="section-rule"></div><div class="grid">
'''
    for effect in applies_to:
        page += f'''
<a class="card" data-update-key="effect:{esc(effect['id'])}" href="../effects/{esc(effect['id'])}.html">
  <div class="card-body">
    <div class="card-top"><h3>{esc(effect['name'])}</h3><span class="tag {effect['availability'].lower()}">{esc(effect['availability'])}</span></div>
    <div class="card-source"><div class="label">Vanilla source</div><div class="value">{esc(source_text(effect))}</div></div>
  </div>
</a>
'''
    if not applies_to:
        page += '<div class="project-empty">No current effect has this modifier mapped yet.</div>'
    page += '</div>' + site_footer(valheim=True) + '</main></body></html>'
    write(WIKI / "modifiers" / f'{modifier["id"]}.html', page)

print(f"Built {len(effects)} effect pages, {len(modifiers)} modifier pages, {len(projects)} project Wiki landings, and the Wiki selector.")
